version: '3'
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./main.py:/app/main.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SQLITE_DB_FILE=/app/result.db
    command: python /app/main.py
    ports:
      - "8000:8000"

  rabbitmq:
      image: rabbitmq:3.7.28-management
      #container_name: rabbitmq
      environment:
          RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret_cookie}
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
      ports:
        - "5672:5672"  #amqp
        - "15672:15672"  #http
        - "15692:15692"  #prometheus
      healthcheck:
        test: [ "CMD", "rabbitmqctl", "status"]
        interval: 5s
        timeout: 20s
        retries: 5